"""empty message

Revision ID: 0470e078fa6c
Revises: 888207d9e167
Create Date: 2023-01-20 12:39:52.717432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0470e078fa6c'
down_revision = '888207d9e167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_is_admin')
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.create_index('ix_user_is_admin', ['is_admin'], unique=False)

    # ### end Alembic commands ###
